INSERT INTO NFSe (
--   idNFSe,
   idCliente,
   Numero,
   CodigoVerificacao,
   DataEmissao,
   BaseCalculo,   
   Aliquota,   
   ValorIss,   
   ValorLiquidoNfse,   
   ValorServicos,   
   ValorDeducoes,   
   ValorPis,   
   ValorCofins,   
   ValorInss,   
   ValorIr,   
   ValorCsll,   
   OutrasRetencoes,   
   DescontoIncondicionado,   
   IssRetido,   
   ItemListaServico,   
   CodigoCnae,   
   Discriminacao,
   Situacao,
   ExigibilidadeISS
   )

VALUES (   
--   1,					--idNFSe,
   1,					--idCliente,
   2,					--Numero,
   '1',					--CodigoVerificacao,
   '2020-02-29',		--DataEmissao,
   100,					--BaseCalculo,   
   2.79,				--Aliquota,   
   2.79,				--ValorIss,   
   100,					--ValorLiquidoNfse,   
   100,					--ValorServicos,   
   0,					--ValorDeducoes,   
   0,					--ValorPis,   
   0,					--ValorCofins,   
   0,					--ValorInss,   
   0,					--ValorIr,   
   0,					--ValorCsll,   
   0,					--OutrasRetencoes,   
   0,					--DescontoIncondicionado,   
   0,					--IssRetido,   
   '1.03',				--ItemListaServico,   
   '6190601',			--CodigoCnae,   
   'LINK FIBRA 100MB',	--Discriminacao,
   0,					--Situacao,
   0					--ExigibilidadeISS
   )
